
#pragma config(Sensor, port4,  gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          left,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          right,         tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor3,          side,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          rightArmMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          leftArmMotor,  tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         claw,          tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static float armRequestedValue;
static bool armMoving;

task armPID(){

			resetMotorEncoder(rightArmMotor);
			//resets motor encoder
			float  pidError;
  	  float  pidLastError;
  	  float  pidIntegral;
   	  float  pidDerivative;
    	float  pidDrive;

			float  pidKp = 1;
			float  pidKi = 0.02;
			float  pidKd = 0.015;

    	pidLastError = 0;
			pidIntegral = 0;

			while(true){
					if(armMoving){
							pidError = (getMotorEncoder(rightArmMotor)) - armRequestedValue;
							if(pidKi != 0)
                {
                		if(abs(pidError) < 100)
                 		 	  pidIntegral = pidIntegral + pidError;
                		else
                  		  pidIntegral = 0;
                }
              pidDerivative = pidError - pidLastError;
  	          pidLastError  = pidError;

  	          pidDrive = (pidKp * pidError) + (pidKi * pidIntegral) + (pidKd * pidDerivative);

              if(pidDrive > 100){
              		pidDrive = 100;
              	}
              if(pidDrive < -100){
              		pidDrive = -100;
              	}
              motor[rightArmMotor] = -pidDrive;

					}
					else{
							pidError = 0;
    			    pidLastError = 0;
  		    	  pidIntegral = 0;
           	  pidDerivative = 0;
         }
         wait1Msec(25);
			}
}


task main()
{
		startTask(armPID);
		armMoving = false;

		while(true) {
			motor[leftArmMotor] = motor[rightArmMotor];

			if(abs(getJoystickValue(ChA)) > 30){
				motor[left] = getJoystickValue(ChA);
			}
			else{
					motor[left] = 0;
			}
			if(abs(getJoystickValue(ChD)) > 30){
				motor[right] = getJoystickValue(ChD);
			}
			else{
					motor[right] = 0;
			}
			if(abs(getJoystickValue(ChB)) > 30 || abs(getJoystickValue(ChC)) > 30){
				motor[side] = fmax(getJoystickValue(ChB), fmax(getJoystickValue(ChB));
			}
			else{
				motor[side] = 0;
			}

			if(abs(getJoystickValue(ChB)) > 20){
					motor[side] = getJoystickValue(ChB);
			}
			else{
					motor[side] = 0;
			}
			if(getJoystickValue(BtnRUp) == 1) {
					motor[claw] = 100;
			}

			else if(getJoystickValue(BtnRDown) == 1) {
					motor[claw] = -100;
			}
			else{
					motor[claw] = 0;
			}
			// && armRequestedValue > -460
			if(getJoystickValue(BtnLUp) == 1 && armRequestedValue > -450) {
				//armRequestedValue -= 0.04;
				motor[rightArmMotor] = -80;
			}

			else if(getJoystickValue(BtnLDown) == 1){// && armRequestedValue < 50) {
				//armRequestedValue += 0.04;
				motor[rightArmMotor] = 60;
			}
			else {
				motor[rightArmMotor] = 0;
			}
			if(getJoystickValue(BtnFDown)){
					armRequestedValue = -110;
			}
			if(getJoystickValue(BtnFUp)){
				motor[left] = -80;
				motor[right] = -80;
				wait10Msec(15);
				armMoving = false;
				motor[leftArmMotor] = 40;
				motor[rightArmMotor] = 40;
				motor[left] = 0;
				motor[right] = 0;
				wait10Msec(38);
				motor[left] = -80;
				motor[right] = -80;
				motor[leftArmMotor] = 0;
				motor[rightArmMotor] = 0;
				wait10Msec(60);
				armRequestedValue = -340;
				armMoving = true;
				}
		}
}
