#pragma config(Motor,  motor5,          topRight,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          bottomRight,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         topLeft,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         bottomLeft,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true) {
		motor[topRight] = getJoystickValue(ChC) - getJoystickValue(ChA) + getJoystickValue(ChB);
		motor[bottomRight] = getJoystickValue(ChC) - getJoystickValue(ChA) - getJoystickValue(ChB);
		motor[topLeft] = getJoystickValue(ChC) + getJoystickValue(ChA) + getJoystickValue(ChB);
		motor[bottomLeft] = getJoystickValue(ChC) + getJoystickValue(ChA) - getJoystickValue(ChB);
	}


}
